//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CWRevolutionEntities : DbContext
    {
        public CWRevolutionEntities()
            : base("name=CWRevolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Req_Desp_Detail> Req_Desp_Detail { get; set; }
        public virtual DbSet<Req_Desp_Header> Req_Desp_Header { get; set; }
        public virtual DbSet<Req_Rebaja_Detail> Req_Rebaja_Detail { get; set; }
        public virtual DbSet<Req_Rebaja_Header> Req_Rebaja_Header { get; set; }
    
        public virtual ObjectResult<SP_Req_MRebaja_Result> SP_Req_MRebaja(Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date, string dept)
        {
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var deptParameter = dept != null ?
                new ObjectParameter("Dept", dept) :
                new ObjectParameter("Dept", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Req_MRebaja_Result>("SP_Req_MRebaja", start_dateParameter, end_dateParameter, deptParameter);
        }
    }
}
