//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req_Rebaja_Header
    {
        public int id { get; set; }
        public string Ncons { get; set; }
        public Nullable<System.DateTime> FechaIn { get; set; }
        public Nullable<System.DateTime> FechaFi { get; set; }
        public string Departamento { get; set; }
        public string Detalle_Gasto { get; set; }
        public string Cuenta_Cargar { get; set; }
        public Nullable<System.DateTime> Fecha_Rep { get; set; }
        public decimal Total { get; set; }
    }
}
