//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req_Desp_Detail
    {
        public int Id { get; set; }
        public string Ncons { get; set; }
        public string Num_parte { get; set; }
        public string Descripcion { get; set; }
        public string Num_serie { get; set; }
        public int Cant_solic { get; set; }
        public int Cant_desp { get; set; }
        public decimal Costo { get; set; }
        public decimal Totaltbl { get; set; }
    }
}
