//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req_Desp_Header
    {
        public string Ncons { get; set; }
        public string Tipo_const { get; set; }
        public string Solicitado_por { get; set; }
        public string Departamento { get; set; }
        public string Sucursal { get; set; }
        public string Desde { get; set; }
        public string Hacia { get; set; }
        public string Referencias { get; set; }
        public string Notas_inventario { get; set; }
        public string Entregado_por { get; set; }
        public string Verificado_por { get; set; }
        public string Recibido_por { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public string TxtEntregadox { get; set; }
        public string TxtVerificadox { get; set; }
        public string TxtRecibidox { get; set; }
    }
}
